const chessPieces = [
  { id: "bk1", title: "king", value: [0,4]},
  { id: "bq1", title: "queen", value: [0,3]},
  { id: "bb1", title: "bishop", value: [0,2]},
  { id: "bb2", title: "bishop", value: [0,5]},
  { id: "bkn1", title: "knight", value: [0,1]},
  { id: "bkn2", title: "knight", value: [0,6]},
  { id: "br1", title: "rook", value: [0,0]},
  { id: "br2", title: "rook", value: [0,7]},
  { id: "bp1", title: "pawn", value: [1,0]},
  { id: "bp2", title: "pawn", value: [1,1]},
  { id: "bp3", title: "pawn", value: [1,2]},
  { id: "bp4", title: "pawn", value: [1,3]},
  { id: "bp5", title: "pawn", value: [1,4]},
  { id: "bp6", title: "pawn", value: [1,5]},
  { id: "bp7", title: "pawn", value: [1,6]},
  { id: "bp8", title: "pawn", value: [1,7]},

  { id: "wk1", title: "king", value: [7,3]},
  { id: "wq1", title: "queen", value: [7,4]},
  { id: "wb1", title: "bishop", value: [7,2]},
  { id: "wb2", title: "bishop", value: [7,5]},
  { id: "wkn1", title: "knight", value: [7,1]},
  { id: "wkn2", title: "knight", value: [7,6]},
  { id: "wr1", title: "rook", value: [7,0]},
  { id: "wr2", title: "rook", value: [7,7]},
  { id: "wp1", title: "pawn", value: [6,0]},
  { id: "wp2", title: "pawn", value: [6,1]},
  { id: "wp3", title: "pawn", value: [6,2]},
  { id: "wp4", title: "pawn", value: [6,3]},
  { id: "wp5", title: "pawn", value: [6,4]},
  { id: "wp6", title: "pawn", value: [6,5]},
  { id: "wp7", title: "pawn", value: [6,6]},
  { id: "wp8", title: "pawn", value: [6,7]},
]

export default chessPieces 